### ISSUE TITLE
add_mlir_tool 无效

### ISSUE THREAD

**Issue by ihnfsax** [KEKE046/mlir-tutorial#2]
使用的是 LLVM 18，add_mlir_tool 似乎不能正常输出可执行文件，换成 add_executable 好了。

**Comment by KEKE046** [comment]
`add_mlir_tool` 不会将 target 加到默认目标里，需要手动 `ninja my-opt` 来编译。如果用 `add_executable` 的话，需要使用 `llvm_update_compile_flags(my-opt)` 来添加 llvm 所需的类型推断参数。
